import pandas as pd
import numpy as np
import json
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# Define official skills (29 skills)
ALL_SKILLS = [
    "Python", "SQL", "Power BI", "Excel", "Tableau", 
    "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", 
    "Java", "JavaScript", "HTML", "CSS", "React", 
    "AWS", "Azure", "Docker", "Kubernetes", "Linux", "Git", 
    "MongoDB", "MySQL", "Networking", "Cyber Security", 
    "Blockchain", "Solidity", "Data Analytics", "Statistics", "Data Visualization"
]

# Mapping of the 20 roles to their relevant skills (from the 29 supported skills)
ROLE_SKILLS_MAP = {
    "Data Analyst": ["SQL", "Excel", "Power BI", "Tableau", "Python", "Data Analytics", "Statistics", "Data Visualization"],
    "Data Scientist": ["Python", "SQL", "Machine Learning", "Deep Learning", "Statistics", "Data Visualization", "Data Analytics"],
    "AI Engineer": ["Python", "Deep Learning", "TensorFlow", "PyTorch", "Machine Learning", "Git"],
    "Machine Learning Engineer": ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "Docker", "Kubernetes", "Git", "SQL"],
    "Cloud Engineer": ["AWS", "Azure", "Linux", "Docker", "Kubernetes", "Networking", "Git"],
    "Cybersecurity Analyst": ["Cyber Security", "Networking", "Linux", "Git", "Python"],
    "Full Stack Developer": ["HTML", "CSS", "JavaScript", "React", "SQL", "MongoDB", "Git"],
    "Software Developer": ["Java", "JavaScript", "Python", "Git", "SQL"],
    "DevOps Engineer": ["Linux", "Docker", "Kubernetes", "Git", "AWS", "Azure", "Networking"],
    "Data Engineer": ["Python", "SQL", "MongoDB", "MySQL", "Data Analytics", "Git"],
    "Business Analyst": ["Excel", "SQL", "Power BI", "Tableau", "Data Analytics", "Data Visualization"],
    "Product Manager": ["Excel", "Power BI", "Data Analytics", "Statistics"],
    "Blockchain Developer": ["Solidity", "Blockchain", "JavaScript", "HTML", "CSS", "Git"],
    "Database Administrator": ["SQL", "MySQL", "MongoDB", "Linux", "Git"],
    "UI UX Designer": ["HTML", "CSS", "JavaScript", "Data Visualization"],
    "Frontend Developer": ["HTML", "CSS", "JavaScript", "React", "Git"],
    "Backend Developer": ["Python", "Java", "SQL", "MongoDB", "MySQL", "Git"],
    "Android Developer": ["Java", "JavaScript", "Git", "Python"],
    "Network Engineer": ["Networking", "Linux", "Cyber Security", "Git"],
    "System Administrator": ["Linux", "Networking", "Cyber Security", "Git", "MySQL"]
}

# High-fidelity metadata for each career (to render beautifully in Section A and Estimator)
CAREER_METADATA = {
    "Data Analyst": {
        "skills": ["SQL", "Excel", "Power BI", "Tableau", "Python", "Data Analytics"],
        "certifications": ["Google Data Analytics Professional", "Microsoft Certified: Power BI Data Analyst (PL-300)", "Coursera Data Science Specialization"],
        "companies": ["Deloitte India", "TCS", "Accenture", "Cognizant", "EY India"],
        "salary_entry": "\u20b93.5L - \u20b95.5L",
        "salary_mid": "\u20b95.5L - \u20b99.5L",
        "salary_senior": "\u20b99.5L - \u20b915.0L",
        "salary_entry_avg": 4.5,
        "salary_mid_avg": 7.5,
        "salary_senior_avg": 12.0,
        "demand": "High",
        "demandPct": 85,
        "growth": "18% YOY",
        "difficulty": "Medium",
        "difficultyVal": 45,
        "learningTime": "3 Months",
        "projects": ["Superstore Sales Dashboard in Power BI", "SQL E-Commerce Queries & Subqueries", "Excel Financial Projection Sheet"]
    },
    "Data Scientist": {
        "skills": ["Python", "SQL", "Machine Learning", "Statistics", "Data Visualization"],
        "certifications": ["Google Advanced Data Analytics", "IBM Data Science Professional Certificate", "Coursera ML by Andrew Ng"],
        "companies": ["Google", "Amazon", "Microsoft", "Meta", "Fractal Analytics"],
        "salary_entry": "\u20b96.0L - \u20b99.5L",
        "salary_mid": "\u20b99.5L - \u20b916.0L",
        "salary_senior": "\u20b916.0L - \u20b925.0L",
        "salary_entry_avg": 7.5,
        "salary_mid_avg": 12.5,
        "salary_senior_avg": 20.5,
        "demand": "Very High",
        "demandPct": 92,
        "growth": "25% YOY",
        "difficulty": "High",
        "difficultyVal": 80,
        "learningTime": "6 Months",
        "projects": ["House Rent Prediction Engine", "Customer Attrition Deep Analysis", "Web Scraped Sentiment Predictor"]
    },
    "AI Engineer": {
        "skills": ["Python", "Deep Learning", "TensorFlow", "PyTorch", "Git"],
        "certifications": ["DeepLearning.AI TensorFlow Developer", "AWS Certified Machine Learning - Specialty"],
        "companies": ["OpenAI", "Microsoft", "Google", "NVIDIA", "Meta"],
        "salary_entry": "\u20b97.0L - \u20b911.0L",
        "salary_mid": "\u20b911.0L - \u20b918.0L",
        "salary_senior": "\u20b918.0L - \u20b930.0L",
        "salary_entry_avg": 9.0,
        "salary_mid_avg": 14.5,
        "salary_senior_avg": 24.0,
        "demand": "Very High",
        "demandPct": 95,
        "growth": "30% YOY",
        "difficulty": "High",
        "difficultyVal": 85,
        "learningTime": "6 Months",
        "projects": ["Text Summarizer NLP Web App", "Object Tracking Smart Camera API", "Fine-tuned Chatbot Interface"]
    },
    "Machine Learning Engineer": {
        "skills": ["Python", "Machine Learning", "TensorFlow", "PyTorch", "Docker"],
        "certifications": ["TensorFlow Developer Certificate", "Google Cloud Professional ML Engineer"],
        "companies": ["NVIDIA", "Intel", "Microsoft", "Google", "Apple"],
        "salary_entry": "\u20b96.5L - \u20b910.0L",
        "salary_mid": "\u20b910.0L - \u20b917.0L",
        "salary_senior": "\u20b917.0L - \u20b928.0L",
        "salary_entry_avg": 8.2,
        "salary_mid_avg": 13.5,
        "salary_senior_avg": 22.5,
        "demand": "Very High",
        "demandPct": 94,
        "growth": "28% YOY",
        "difficulty": "High",
        "difficultyVal": 82,
        "learningTime": "6 Months",
        "projects": ["End-to-End MLOps Model Deploy", "Dockerized Prediction Microservice", "Realtime Fraud Detection Model"]
    },
    "Cloud Engineer": {
        "skills": ["AWS", "Azure", "Linux", "Docker", "Kubernetes", "Networking"],
        "certifications": ["AWS Solutions Architect Associate", "Microsoft Certified: Azure Administrator Associate", "CKA (Certified Kubernetes Administrator)"],
        "companies": ["Amazon AWS", "Microsoft Azure", "IBM", "Red Hat", "Infosys"],
        "salary_entry": "\u20b94.5L - \u20b97.5L",
        "salary_mid": "\u20b97.5L - \u20b913.0L",
        "salary_senior": "\u20b913.0L - \u20b922.0L",
        "salary_entry_avg": 6.0,
        "salary_mid_avg": 10.2,
        "salary_senior_avg": 17.5,
        "demand": "High",
        "demandPct": 88,
        "growth": "21% YOY",
        "difficulty": "Medium",
        "difficultyVal": 55,
        "learningTime": "4 Months",
        "projects": ["Multi-tier Secure AWS Architecture", "Kubernetes Load Balancer Deploy", "Terraform Infrastructure as Code"]
    },
    "Cybersecurity Analyst": {
        "skills": ["Cyber Security", "Networking", "Linux", "Git", "Python"],
        "certifications": ["CompTIA Security+", "CEH (Certified Ethical Hacker)", "CISSP"],
        "companies": ["CrowdStrike", "Palo Alto Networks", "Deloitte India", "Wipro", "TCS"],
        "salary_entry": "\u20b94.5L - \u20b97.0L",
        "salary_mid": "\u20b97.0L - \u20b912.0L",
        "salary_senior": "\u20b912.0L - \u20b919.0L",
        "salary_entry_avg": 5.8,
        "salary_mid_avg": 9.5,
        "salary_senior_avg": 15.5,
        "demand": "Very High",
        "demandPct": 90,
        "growth": "26% YOY",
        "difficulty": "High",
        "difficultyVal": 72,
        "learningTime": "5 Months",
        "projects": ["Custom Port Scanner Utility", "Intrusion Alert log Analyzer", "Secure Cryptographic Chat Server"]
    },
    "Full Stack Developer": {
        "skills": ["HTML", "CSS", "JavaScript", "React", "SQL", "MongoDB"],
        "certifications": ["Meta Full-Stack Developer Professional", "Udemy Modern Web Dev Bootcamp"],
        "companies": ["Accenture", "Infosys", "Wipro", "Cognizant", "Tech Mahindra"],
        "salary_entry": "\u20b94.0L - \u20b96.5L",
        "salary_mid": "\u20b96.5L - \u20b912.0L",
        "salary_senior": "\u20b912.0L - \u20b920.0L",
        "salary_entry_avg": 5.2,
        "salary_mid_avg": 9.2,
        "salary_senior_avg": 16.0,
        "demand": "Very High",
        "demandPct": 91,
        "growth": "22% YOY",
        "difficulty": "Medium",
        "difficultyVal": 50,
        "learningTime": "6 Months",
        "projects": ["Interactive Task Management Dashboard", "Full Stack Blogging Platform", "E-commerce Front & Back Store"]
    },
    "Software Developer": {
        "skills": ["Java", "JavaScript", "Python", "Git", "SQL"],
        "certifications": ["Oracle Java Programmer Certification", "Microsoft Certified: Azure Developer Associate"],
        "companies": ["Adobe", "Oracle", "Microsoft", "TCS", "Capgemini"],
        "salary_entry": "\u20b94.0L - \u20b96.5L",
        "salary_mid": "\u20b96.5L - \u20b911.5L",
        "salary_senior": "\u20b911.5L - \u20b918.0L",
        "salary_entry_avg": 5.2,
        "salary_mid_avg": 9.0,
        "salary_senior_avg": 14.8,
        "demand": "High",
        "demandPct": 86,
        "growth": "18% YOY",
        "difficulty": "Medium",
        "difficultyVal": 60,
        "learningTime": "5 Months",
        "projects": ["Visual Algorithm Solving Utility", "Desktop Database Inventory App", "Multi-threaded Link Crawler"]
    },
    "DevOps Engineer": {
        "skills": ["Linux", "Docker", "Kubernetes", "Git", "AWS", "Networking"],
        "certifications": ["AWS DevOps Engineer Professional", "Docker Certified Associate (DCA)"],
        "companies": ["Red Hat", "Amazon AWS", "TCS", "Accenture", "HCLTech"],
        "salary_entry": "\u20b95.0L - \u20b98.0L",
        "salary_mid": "\u20b98.0L - \u20b914.0L",
        "salary_senior": "\u20b914.0L - \u20b922.0L",
        "salary_entry_avg": 6.5,
        "salary_mid_avg": 11.0,
        "salary_senior_avg": 18.0,
        "demand": "Very High",
        "demandPct": 93,
        "growth": "24% YOY",
        "difficulty": "High",
        "difficultyVal": 78,
        "learningTime": "5 Months",
        "projects": ["Automated CI/CD Pipeline (Jenkins & Docker)", "Server Status Dashboard via Bash script", "Kubernetes Cluster Auto-Scale Setup"]
    },
    "Data Engineer": {
        "skills": ["Python", "SQL", "MongoDB", "MySQL", "Data Analytics", "Git"],
        "certifications": ["Google Cloud Professional Data Engineer", "IBM Data Engineering Specialization"],
        "companies": ["Snowflake", "Databricks", "TCS", "Cognizant", "LTIMindtree"],
        "salary_entry": "\u20b95.0L - \u20b98.0L",
        "salary_mid": "\u20b98.0L - \u20b914.0L",
        "salary_senior": "\u20b914.0L - \u20b922.0L",
        "salary_entry_avg": 6.5,
        "salary_mid_avg": 11.0,
        "salary_senior_avg": 18.0,
        "demand": "High",
        "demandPct": 87,
        "growth": "19% YOY",
        "difficulty": "High",
        "difficultyVal": 70,
        "learningTime": "4 Months",
        "projects": ["Automated Data Warehousing Script", "ETL Log Data Pipeline to MySQL", "Data Warehouse Query Tuning Engine"]
    },
    "Business Analyst": {
        "skills": ["Excel", "SQL", "Power BI", "Tableau", "Data Analytics"],
        "certifications": ["IIBA Certified Business Analysis (CBAP)", "PMI-PBA Certification"],
        "companies": ["Deloitte India", "EY India", "KPMG India", "PwC India", "TCS"],
        "salary_entry": "\u20b94.0L - \u20b96.0L",
        "salary_mid": "\u20b96.0L - \u20b910.5L",
        "salary_senior": "\u20b910.5L - \u20b916.0L",
        "salary_entry_avg": 5.0,
        "salary_mid_avg": 8.2,
        "salary_senior_avg": 13.2,
        "demand": "High",
        "demandPct": 84,
        "growth": "15% YOY",
        "difficulty": "Medium",
        "difficultyVal": 40,
        "learningTime": "3 Months",
        "projects": ["Company Performance Forecast Deck", "Product Functional Specs Blueprint", "Agile Task Speed Metrics Panel"]
    },
    "Product Manager": {
        "skills": ["Excel", "Power BI", "Data Analytics", "Statistics"],
        "certifications": ["Product School Certified Manager", "Pragmatic Institute Certified Professional"],
        "companies": ["Google", "Uber", "Paytm", "Flipkart", "Amazon"],
        "salary_entry": "\u20b96.0L - \u20b99.5L",
        "salary_mid": "\u20b99.5L - \u20b916.0L",
        "salary_senior": "\u20b916.0L - \u20b926.0L",
        "salary_entry_avg": 7.8,
        "salary_mid_avg": 12.8,
        "salary_senior_avg": 21.0,
        "demand": "High",
        "demandPct": 86,
        "growth": "20% YOY",
        "difficulty": "High",
        "difficultyVal": 68,
        "learningTime": "4 Months",
        "projects": ["Figma Dynamic User Flow Canvas", "Market Penetration Roadmap Sheet", "User Persona Research Report"]
    },
    "Blockchain Developer": {
        "skills": ["Solidity", "Blockchain", "JavaScript", "HTML", "CSS", "Git"],
        "certifications": ["ConsenSys Solidity Academy", "Certified Blockchain Developer (CBP)"],
        "companies": ["Coinbase", "Polygon", "ConsenSys", "TCS", "Tech Mahindra"],
        "salary_entry": "\u20b96.5L - \u20b910.0L",
        "salary_mid": "\u20b910.0L - \u20b917.0L",
        "salary_senior": "\u20b917.0L - \u20b927.0L",
        "salary_entry_avg": 8.2,
        "salary_mid_avg": 13.5,
        "salary_senior_avg": 22.0,
        "demand": "High",
        "demandPct": 85,
        "growth": "22% YOY",
        "difficulty": "High",
        "difficultyVal": 80,
        "learningTime": "5 Months",
        "projects": ["Solidity Electronic Voting Smart Contract", "Decentralized NFT Minting DApp", "Web3 CLI Wallet Utility"]
    },
    "Database Administrator": {
        "skills": ["SQL", "MySQL", "MongoDB", "Linux", "Git"],
        "certifications": ["Oracle Database Administration Professional", "Microsoft Certified: Azure Database Administrator"],
        "companies": ["Oracle", "Microsoft", "Wipro", "Infosys", "TCS"],
        "salary_entry": "\u20b93.5L - \u20b95.5L",
        "salary_mid": "\u20b95.5L - \u20b99.5L",
        "salary_senior": "\u20b99.5L - \u20b915.0L",
        "salary_entry_avg": 4.5,
        "salary_mid_avg": 7.5,
        "salary_senior_avg": 12.2,
        "demand": "High",
        "demandPct": 80,
        "growth": "14% YOY",
        "difficulty": "Medium",
        "difficultyVal": 50,
        "learningTime": "4 Months",
        "projects": ["Automatic Database Replication Script", "Server Index Optimization Index Profile", "Large-scale Database Migration Tool"]
    },
    "UI UX Designer": {
        "skills": ["HTML", "CSS", "JavaScript", "Data Visualization"],
        "certifications": ["Google UX Design Professional Certificate", "Interaction Design Foundation Certificate"],
        "companies": ["Figma", "Adobe", "Cognizant", "Infosys", "LTIMindtree"],
        "salary_entry": "\u20b93.5L - \u20b96.0L",
        "salary_mid": "\u20b96.0L - \u20b910.0L",
        "salary_senior": "\u20b910.0L - \u20b916.0L",
        "salary_entry_avg": 4.8,
        "salary_mid_avg": 8.0,
        "salary_senior_avg": 13.0,
        "demand": "High",
        "demandPct": 85,
        "growth": "18% YOY",
        "difficulty": "Medium",
        "difficultyVal": 45,
        "learningTime": "3 Months",
        "projects": ["Dynamic Fintech Mobile Prototype", "E-commerce Interface Wireframes Deck", "User Interaction Usability Study"]
    },
    "Frontend Developer": {
        "skills": ["HTML", "CSS", "JavaScript", "React", "Git"],
        "certifications": ["Meta Frontend Developer Professional", "W3Schools Frontend Developer Certification"],
        "companies": ["Wipro", "TCS", "Accenture", "Cognizant", "Capgemini"],
        "salary_entry": "\u20b93.5L - \u20b96.0L",
        "salary_mid": "\u20b96.0L - \u20b910.5L",
        "salary_senior": "\u20b910.5L - \u20b916.5L",
        "salary_entry_avg": 4.8,
        "salary_mid_avg": 8.2,
        "salary_senior_avg": 13.5,
        "demand": "Very High",
        "demandPct": 89,
        "growth": "20% YOY",
        "difficulty": "Medium",
        "difficultyVal": 48,
        "learningTime": "4 Months",
        "projects": ["Real-time Weather Dashboard", "CSS Glassmorphic Interactive Gallery", "Static Single Page App Layout"]
    },
    "Backend Developer": {
        "skills": ["Python", "Java", "SQL", "MongoDB", "MySQL", "Git"],
        "certifications": ["Meta Backend Developer Professional", "Spring Certified Professional"],
        "companies": ["Amazon", "Microsoft", "Oracle", "IBM", "TCS"],
        "salary_entry": "\u20b94.0L - \u20b96.5L",
        "salary_mid": "\u20b96.5L - \u20b912.0L",
        "salary_senior": "\u20b912.0L - \u20b919.0L",
        "salary_entry_avg": 5.2,
        "salary_mid_avg": 9.2,
        "salary_senior_avg": 15.5,
        "demand": "High",
        "demandPct": 87,
        "growth": "19% YOY",
        "difficulty": "Medium",
        "difficultyVal": 58,
        "learningTime": "5 Months",
        "projects": ["Microservice REST API Gateway", "Database Security Vault Handler", "Robust Threaded Task Broker"]
    },
    "Android Developer": {
        "skills": ["Java", "JavaScript", "Git", "Python"],
        "certifications": ["Google Associate Android Developer", "Udacity Android Nanodegree"],
        "companies": ["Samsung India", "Google", "Paytm", "Zomato", "Swiggy"],
        "salary_entry": "\u20b94.0L - \u20b96.5L",
        "salary_mid": "\u20b96.5L - \u20b911.5L",
        "salary_senior": "\u20b911.5L - \u20b918.0L",
        "salary_entry_avg": 5.2,
        "salary_mid_avg": 9.0,
        "salary_senior_avg": 14.8,
        "demand": "High",
        "demandPct": 82,
        "growth": "16% YOY",
        "difficulty": "Medium",
        "difficultyVal": 62,
        "learningTime": "5 Months",
        "projects": ["Google Material Android News Reader", "Off-grid SQL database Diary", "BLE Smart Hub scanner App"]
    },
    "Network Engineer": {
        "skills": ["Networking", "Linux", "Cyber Security", "Git"],
        "certifications": ["Cisco CCNA (200-301)", "CompTIA Network+"],
        "companies": ["Cisco India", "Airtel", "Jio", "TCS", "Infosys"],
        "salary_entry": "\u20b93.5L - \u20b95.5L",
        "salary_mid": "\u20b95.5L - \u20b99.5L",
        "salary_senior": "\u20b99.5L - \u20b914.5L",
        "salary_entry_avg": 4.5,
        "salary_mid_avg": 7.5,
        "salary_senior_avg": 12.0,
        "demand": "High",
        "demandPct": 78,
        "growth": "12% YOY",
        "difficulty": "Medium",
        "difficultyVal": 52,
        "learningTime": "3 Months",
        "projects": ["Cisco Packet Tracer Architecture Topology", "Secure Virtual Private Routing Hub", "Wireshark Packet Analysis Log"]
    },
    "System Administrator": {
        "skills": ["Linux", "Networking", "Cyber Security", "Git", "MySQL"],
        "certifications": ["Red Hat Certified System Administrator (RHCSA)", "CompTIA Linux+"],
        "companies": ["Red Hat", "TCS", "Wipro", "Infosys", "Cognizant"],
        "salary_entry": "\u20b93.5L - \u20b95.5L",
        "salary_mid": "\u20b95.5L - \u20b99.5L",
        "salary_senior": "\u20b99.5L - \u20b914.5L",
        "salary_entry_avg": 4.5,
        "salary_mid_avg": 7.5,
        "salary_senior_avg": 12.0,
        "demand": "Medium",
        "demandPct": 74,
        "growth": "11% YOY",
        "difficulty": "Medium",
        "difficultyVal": 50,
        "learningTime": "4 Months",
        "projects": ["Server Setup Automation Ansible Script", "Domain Group controller Access Manager", "Linux Kernel Shell Logs Script"]
    }
}

def train_and_export():
    import json
    export_payload = {
        "all_skills": ALL_SKILLS,
        "careers": CAREER_METADATA
    }
    
    print("Writing metadata parameters to js/model_data.js...")
    js_content = f"// Automatically generated by train_model.py\nconst MODEL_DATA = {json.dumps(export_payload, indent=2)};\n"
    
    with open("js/model_data.js", "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print("Export complete. model_data.js contains career definitions & metadata.")

if __name__ == "__main__":
    train_and_export()
